language: java
services:
- postgresql
before_script:
- psql -c 'create database invoicify;' -U postgres
- psql -c "CREATE USER testuser WITH PASSWORD 'password';" -U postgres
deploy:
  provider: heroku
  api_key:
    secure: cZ1O3sMnqHXba0WHJwT28b1L9XwHY/tY9w68l27h00fO/TE7rnDSEU1lvcNXo604OUdBqg8+wWEZyF3P76GYnyAm11SEy5veSRCdqNv/OioGdAsOj8PJYEKejodBCGt9Gogo98oobBHAkxLxp8Cb4HS1VBMBKYXP4vuTRI2jGLhFzjeBYq9ZT/Z2rDEAPQ0tUq56PtTrPU1u4fveNXBLcLJdwqHuJy94Nm1YhAQPKVO9GmLx2o16ZRo0K2zq6fB4JcsVPFnTUGIaIYNoKAFe/dszQrkD/cvqKFK2wSg6ihFWH+HGtcy4Z/lBJkSI+w4LLHQpGfpa8+J5cHKgibWLNoB5PyxwsmQqVT3K2cxgo59k3Z7jg7QAEQ6CTVwCAnUvGy+NwR1tqXmif+KfmaD4F+cpZviaFSAGLF/4cv1H7xDn0ZK4d9V+xEXO9oS59oHHIPx4NrFkA7ZK1dWRgWgf5aNX4uzYL6ditycVAgupmdKy1H0QM1eD3MNynlJfxs2WRN4WZYZa7U2cXhAnjTdhEdsBUertkXgxoXUzQL/ZE1Cc5MAwZly3uq+h7XNsXGh4PlduYUiBkw/uHY2Kgm/6h/HvSqUFmjjCl6qpkvD0AfLR0+dNHMWzK8BvxW2FgifoSlbu0XfFkSNqmSjAJIkXHqNysYrBQOqKxUB5Ogphtdc=
  app: limitless-reaches-90243
  on:
    repo: samadr1013/invoicify-final
