language: java
services:
- postgresql
before_script:
- psql -c 'create database invoicify;' -U postgres
- psql -c "CREATE USER YOUR_DB_USER WITH PASSWORD 'YOUR_DB_USER_PASSWORD';" -U postgres
deploy:
  api_key:
    secure: FtNxBHOxl5rNOXUm9pcros/FMDG3vDYVWlo7LiqmT4Y/5vKHwB5vKssAOUMlp75V7GhQx7gG/knCIDI6vWmyaxSNau1/e6//fduJmMin1Vv8feVnuc42rOfUE+hDUmHeko9VLyNScX7F4Qkpsv6Fbu8u0kgxFsEj6etj97RErXgRpFUXKSHoc7kkbb6LgNd1kY9n2U1ehCwVFSoZlmBS5K1xCVhZO9QKMtDBWhD/hjle29DQmqtgxVk81FgFUvuKnljkc18TBq1OnfWmrKMfOD/51WOGdJghMZXQrU6L6Nms8juvPHA67XmdxrEMZ4QtqFL4v4vSJQm8gitOVl340XILrwHxAGWUSclW6+3GEkWAxHKKchE3m3fKa0qKG7DPQF3em25Wax1KNvTUvDvhoVjyIbIAwf/+QVGZSUOp5E4+mUjKrm2+paIQXJ/+nx9yylyHv5pcqNFOsiqYeuJ85gf9/ABET4ePbXSdX2v8zI2MLbnp1Rr5Nr7fGUn3sPy35N3EbiQovz5nmufEE+WgCK+yQ5kvwPOYF3w2GPBKS0TaLSfrox2dn94pIPf4xeaHrY+I/MFQFh0pyt/LqTlP9gDDwA/PTWK0R6ieU1QZBS0nv0JPUVbBrtWJ0/PDYgdewuFNdIeKzxvAW4G3k9sLyu0wywBK5kqXhUveyQWDhKg=
