language: java
services:
- postgresql
before_script:
- psql -c 'create database invoicify;' -U postgres
- psql -c "CREATE USER testuser WITH PASSWORD 'password';" -U postgres
deploy:
  provider: heroku
  api_key:
    secure: efg2VE+kyzklqjOx0foBe4r/LeCKdsiZet5/Y/ucWXbrCXLOtnLvCn4BUqead2uqoA3WoXl7tDpZSrQexHvBfFL0wCUEW1trRKomhXDmwcAaPawlpjL81pGuXoqdgF105sth0oDK2653+xm4UV0S/EjS4VId72z2fGIOGsmwHs655RyzZbPLZQUTDCihFsf77x2HDERPdh3pXherW+Tegp4IWfRXkz4uXAQej8zZeEhs699OqcEj7vga5waakP2eUebWrKRkr6oaBE7sTug/gcqaq+Smc+Hq+Xiwi9ZCUILk3cOkW0NlubMXF9llNe/O8if0UBIZzMjeN7xg0e7sq2U8klpcGNbDkoPlOhHA4UZrOd70PLdHnTkEx8wXFo7nbTCUDNjiJEMD5kzig+xrrMHZzhicsqL5u2pmzsZG6KeWJOgYOpV5y6GQUOgzESy0PSHAsHl7uh9TjlD4P4FleTOepsJvB15+a25oaP+OoGhucCDVI8b3LTN1CsKWfIWPasG066hEuTDvo3SbKbVL4Fx/nblDF7wTdhwixsij6V+ui3oP9VT8qgwwNxEyfx+I48WRYRd6H5U4Kz9BLDmtmDyt5hY8EX2rAZLGDZMdxv33G4hfTPvtf+6CxrqGA7xpUSU/ro+pDoB53qorl2B/N3caglYzc9YMmPHP1KUemuc=
  app: shielded-beach-91288
  on:
    repo: samadr1013/invoicify-final
